# Generated by Django 5.0.7 on 2024-08-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('paternal_surname', models.CharField(max_length=128)),
                ('maternal_surname', models.CharField(max_length=128)),
                ('street_and_number', models.CharField(max_length=256)),
                ('neighborhood', models.CharField(max_length=256)),
                ('zip_code', models.IntegerField()),
                ('municipality', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.IntegerField()),
                ('nationality', models.CharField(max_length=128)),
                ('sex', models.CharField(max_length=1)),
                ('level', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.career')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.institute')),
            ],
        ),
    ]
