# Generated by Django 5.1 on 2024-08-15 02:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('academy_president', models.CharField(max_length=256)),
                ('department_head', models.CharField(max_length=256)),
                ('created_at', models.DateField()),
                ('origin_syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outer_syllabus', to='institutes.syllabus')),
                ('receiver_syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_syllabus', to='institutes.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Equivalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('equivalence', models.ManyToManyField(to='students.student')),
                ('origin_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outer_subjects', to='institutes.subject')),
                ('receiver_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_subjects', to='institutes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('created_at', models.DateField()),
                ('to_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.career')),
                ('to_institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.institute')),
            ],
        ),
    ]
