# Generated by Django 5.1 on 2024-08-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equivalence',
            old_name='equivalence',
            new_name='student',
        ),
    ]
