# Generated by Django 5.1 on 2024-08-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0002_rename_equivalence_equivalence_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
    ]
