# Generated by Django 5.1 on 2024-08-28 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0004_request_created_at'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='request', serialize=False, to='students.student'),
        ),
    ]
