# Generated by Django 5.1 on 2024-08-30 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0005_alter_request_student'),
        ('institutes', '0003_rename_syllabus_subject_career'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='academy_president',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='department_head',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='student',
        ),
        migrations.RemoveField(
            model_name='equivalence',
            name='student',
        ),
        migrations.AddField(
            model_name='analysis',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equivalence',
            name='analysis',
            field=models.ManyToManyField(to='equivalences.analysis'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='origin_syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_syllabus', to='institutes.syllabus'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='receiver_syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_syllabus', to='institutes.syllabus'),
        ),
        migrations.CreateModel(
            name='DocAnalysis',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('academy_president', models.CharField(max_length=256)),
                ('department_head', models.CharField(max_length=256)),
                ('created_at', models.DateField()),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equivalences.analysis')),
            ],
        ),
    ]
