# Generated by Django 5.1 on 2024-08-30 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0006_remove_analysis_academy_president_and_more'),
        ('institutes', '0003_rename_syllabus_subject_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalence',
            name='receiver_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_subjects', to='institutes.subject'),
        ),
    ]
