# Generated by Django 5.1 on 2024-08-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0007_alter_equivalence_receiver_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalence',
            name='origin_subject',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equivalence',
            name='receiver_subject',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
    ]
