# Generated by Django 5.1 on 2024-08-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0008_alter_equivalence_origin_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalence',
            name='receiver_subject',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
