# Generated by Django 5.1 on 2024-08-31 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0009_alter_equivalence_receiver_subject'),
        ('institutes', '0003_rename_syllabus_subject_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equivalence',
            name='analysis',
        ),
        migrations.AlterField(
            model_name='equivalence',
            name='origin_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_subject', to='institutes.subject'),
        ),
        migrations.AlterField(
            model_name='equivalence',
            name='receiver_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_subject', to='institutes.subject'),
        ),
        migrations.AddField(
            model_name='equivalence',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equivalences.analysis'),
        ),
    ]
