# Generated by Django 5.1 on 2024-08-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0010_remove_equivalence_analysis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equivalence',
        ),
    ]
