# Generated by Django 5.1 on 2024-09-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0012_equivalence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docanalysis',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
