# Generated by Django 5.0.7 on 2024-08-03 17:52

from django.db import migrations

def populate_roles(apps, schemaeditor):
  entries = {
    "Administrator": "Can create syllabus, add students, and perform equivalencies",
    "Student": "Can view the announcement and upload personal files",
  }
  Role = apps.get_model("accounts", "Role")
  for key, value in entries.items():
    role_obj = Role(name=key, description=value)
    role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240803_0100'),
    ]

    operations = [
      migrations.RunPython(populate_roles)
    ]
