# Generated by Django 5.0.7 on 2024-08-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
    ]
