# Generated by Django 5.1 on 2024-08-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='career',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='syllabus', serialize=False, to='institutes.career'),
        ),
    ]
