# Generated by Django 5.1 on 2024-08-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_syllabus_career'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='syllabus',
            new_name='career',
        ),
    ]
